"""Core data models using Pydantic v2."""

from datetime import datetime
from enum import Enum
from typing import Optional

from pydantic import BaseModel, Field


# ─── Enums ────────────────────────────────────────────────────────────────────


class SignalDirection(str, Enum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    NEUTRAL = "NEUTRAL"


class OrderSide(str, Enum):
    BUY = "BUY"
    SELL = "SELL"


class MarketStatus(str, Enum):
    OPEN = "OPEN"
    CLOSED = "CLOSED"
    PRE_MARKET = "PRE_MARKET"
    AFTER_HOURS = "AFTER_HOURS"
    HOLIDAY = "HOLIDAY"


# ─── OHLCV ────────────────────────────────────────────────────────────────────


class OHLCVBar(BaseModel):
    """A single OHLCV candle."""
    ticker: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    interval: str = "1d"  # e.g. '1m', '5m', '1h', '1d'


class Quote(BaseModel):
    """Real-time snapshot quote."""
    ticker: str
    timestamp: datetime
    price: float
    change: float = 0.0
    change_pct: float = 0.0
    volume: float = 0.0
    bid: Optional[float] = None
    ask: Optional[float] = None


# ─── Signal ───────────────────────────────────────────────────────────────────


class Signal(BaseModel):
    """Trading signal generated by a strategy."""
    ticker: str
    timestamp: datetime
    direction: SignalDirection
    confidence: float = Field(ge=0.0, le=1.0)
    strategy: str
    indicators_used: list[str] = Field(default_factory=list)
    reasoning: str = ""
    price_at_signal: float
    expiration: Optional[datetime] = None

    def is_expired(self, now: datetime | None = None) -> bool:
        if self.expiration is None:
            return False
        now = now or datetime.now()
        return now > self.expiration


# ─── Backtest ─────────────────────────────────────────────────────────────────


class BacktestResult(BaseModel):
    """Result of a strategy backtest."""
    strategy: str
    ticker: str
    start_date: datetime
    end_date: datetime
    initial_capital: float
    final_capital: float
    total_return: float          # as fraction, e.g., 0.15 = 15%
    total_return_pct: float
    cagr: float                   # Compound Annual Growth Rate
    sharpe_ratio: float
    max_drawdown: float           # as negative fraction
    max_drawdown_pct: float
    win_rate: float               # fraction of winning trades
    profit_factor: float          # gross_profit / gross_loss
    total_trades: int
    winning_trades: int
    losing_trades: int
    avg_win: float
    avg_loss: float
    best_trade: float
    worst_trade: float
    benchmark_return: Optional[float] = None   # SPY buy-and-hold over same period


class Trade(BaseModel):
    """A single completed trade in a backtest."""
    entry_time: datetime
    exit_time: datetime
    ticker: str
    side: OrderSide
    entry_price: float
    exit_price: float
    quantity: float
    pnl: float
    pnl_pct: float
    holding_bars: int = 0


# ─── Market ───────────────────────────────────────────────────────────────────


class MarketInfo(BaseModel):
    """Current market session information."""
    status: MarketStatus
    current_time: datetime
    next_open: Optional[datetime] = None
    next_close: Optional[datetime] = None
    timezone: str = "America/New_York"
